/**
 * RW-021: Client env loader fail-fast contract.
 *
 * Guards `src/lib/env.ts`:
 *   1. Throws `EnvConfigError` synchronously when any required var is missing.
 *   2. Throws when `VITE_SUPABASE_URL` is present but not a parseable URL.
 *   3. Returns a frozen, validated `env` object when all required vars are valid.
 *   4. No consumer in `src/` (other than `env.ts` and the auto-generated supabase
 *      client) reads `import.meta.env.VITE_SUPABASE_*` directly. This prevents
 *      regression of the original RW-021 bug where pages built bad URLs from a
 *      missing env var deep inside React Query, producing
 *      "Failed to construct 'URL': Invalid URL".
 */
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';

describe('RW-021: env loader fail-fast', () => {
  beforeEach(() => {
    vi.resetModules();
  });

  afterEach(() => {
    vi.unstubAllEnvs();
    vi.resetModules();
  });

  it('throws EnvConfigError when VITE_SUPABASE_URL is missing', async () => {
    vi.stubEnv('VITE_SUPABASE_URL', '');
    vi.stubEnv('VITE_SUPABASE_PUBLISHABLE_KEY', 'anon-key');
    vi.stubEnv('VITE_SUPABASE_PROJECT_ID', 'project-id');

    await expect(async () => {
      await import('@/lib/env');
    }).rejects.toMatchObject({
      name: 'EnvConfigError',
      missing: expect.arrayContaining(['VITE_SUPABASE_URL']),
    });
  });

  it('throws EnvConfigError when VITE_SUPABASE_PUBLISHABLE_KEY is missing', async () => {
    vi.stubEnv('VITE_SUPABASE_URL', 'https://example.supabase.co');
    vi.stubEnv('VITE_SUPABASE_PUBLISHABLE_KEY', '');
    vi.stubEnv('VITE_SUPABASE_PROJECT_ID', 'project-id');

    await expect(async () => {
      await import('@/lib/env');
    }).rejects.toMatchObject({
      name: 'EnvConfigError',
      missing: expect.arrayContaining(['VITE_SUPABASE_PUBLISHABLE_KEY']),
    });
  });

  it('throws EnvConfigError when VITE_SUPABASE_URL is not a valid URL', async () => {
    vi.stubEnv('VITE_SUPABASE_URL', 'not-a-url');
    vi.stubEnv('VITE_SUPABASE_PUBLISHABLE_KEY', 'anon-key');
    vi.stubEnv('VITE_SUPABASE_PROJECT_ID', 'project-id');

    await expect(async () => {
      await import('@/lib/env');
    }).rejects.toMatchObject({
      name: 'EnvConfigError',
      invalid: expect.arrayContaining([
        expect.stringContaining('VITE_SUPABASE_URL'),
      ]),
    });
  });

  it('returns a frozen env object with canonical functions base URL when valid', async () => {
    vi.stubEnv('VITE_SUPABASE_URL', 'https://example.supabase.co');
    vi.stubEnv('VITE_SUPABASE_PUBLISHABLE_KEY', 'anon-key');
    vi.stubEnv('VITE_SUPABASE_PROJECT_ID', 'project-id');

    const mod = await import('@/lib/env');
    expect(mod.env.SUPABASE_URL).toBe('https://example.supabase.co');
    expect(mod.env.SUPABASE_PUBLISHABLE_KEY).toBe('anon-key');
    expect(mod.env.SUPABASE_PROJECT_ID).toBe('project-id');
    expect(Object.isFrozen(mod.env)).toBe(true);
    expect(mod.getFunctionsBaseUrl()).toBe('https://example.supabase.co/functions/v1');
  });

  it('no source file other than env.ts and the auto-generated supabase client reads VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY directly', () => {
    const ALLOWED = new Set([
      'src/lib/env.ts',
      // Auto-generated by Supabase tooling — has hardcoded values, no env read.
      'src/integrations/supabase/client.ts',
      // This test file itself stubs the vars.
      'src/test/rw021-env-loader-fail-fast.test.ts',
    ]);
    const VIOLATION_RE = /import\.meta\.env\.VITE_SUPABASE_(URL|PUBLISHABLE_KEY|PROJECT_ID)/;

    const violations: string[] = [];
    function walk(dir: string) {
      for (const entry of readdirSync(dir)) {
        const full = join(dir, entry);
        const st = statSync(full);
        if (st.isDirectory()) {
          if (entry === 'node_modules' || entry.startsWith('.')) continue;
          walk(full);
          continue;
        }
        if (!/\.(ts|tsx)$/.test(entry)) continue;
        const rel = full.replace(/\\/g, '/');
        if (ALLOWED.has(rel)) continue;
        const content = readFileSync(full, 'utf8');
        if (VIOLATION_RE.test(content)) violations.push(rel);
      }
    }
    walk('src');
    expect(violations).toEqual([]);
  });
});