/**
 * overshoot-broker-interfaces — Broker API contracts for the overshoot strategy.
 *
 * FP-069 W3.2.a (ACT-459.a) — minimal used-surface transcription of the
 * longshort-broker-interfaces types needed by the six overshoot-broker
 * adapters (paper-client + submitter + canceller + fill-fetcher +
 * position-fetcher + shortability-fetcher). Blocker B1 ruling (a): the
 * overshoot tree OWNS its execution contract; nothing here imports from
 * ../longshort-broker-interfaces.ts. HttpFetch precedent (W1b ACT-456)
 * is cited — same discipline (leaf tree redeclares the shape it consumes).
 *
 * SIGNATURE-IDENTICAL to the corresponding types in
 *   supabase/functions/_shared/longshort-broker-interfaces.ts
 * (BrokerPosition:25, BrokerPositionFetcher:57, BrokerShortability:123,
 *  BrokerShortabilityFetcher:133, BrokerOrderRequest:501,
 *  BrokerOrderAcceptance:522, BrokerOrderSubmitter:545,
 *  BrokerFillResult:564, BrokerFillFetcher:572, BrokerOrderCanceller:582).
 *
 * Signatures pinned so overshoot adapters can be smoke-checked against
 * shared mock fixtures during W3 sub-turns without adapter shims. Longshort
 * drift downstream is allowed — the overshoot tree is the leaf owner here.
 *
 * DEC-034 propagation posture (verbatim inheritance):
 *   (3) errors propagate as typed throws — NO swallow + phantom-success.
 *   (4) NO wall-clock leakage in the interface — `ts: Date` is injected.
 *   (2) NO sentinel returns — explicit success/failure branches only.
 *
 * B2 discipline (ruling): NO CID / intent / state-machine content in this
 * file. Those contracts land at W3.4 when the overshoot execution model is
 * ratified. This file exposes broker I/O primitives ONLY.
 */

// ────────────────────────────────────────────────────────────────────
// Position surface (adapter: alpaca-position-fetcher.ts)
// ────────────────────────────────────────────────────────────────────

/** Position snapshot as returned by the broker. */
export interface BrokerPosition {
  symbol: string;
  /** Signed: negative for short positions. */
  qty: number;
  /** Dollars per share. */
  avg_entry_price: number;
  /** Broker-stamped snapshot time (derived from injected `ts`). */
  fetched_at: Date;
  /** Dollars; signed (negative for shorts). Alpaca /v2/positions native. */
  market_value?: number;
  /** Dollars per share; last mark. Alpaca /v2/positions native. */
  current_price?: number;
  /** Dollars; since-fill unrealized P&L per Alpaca. Typed-absence — NEVER fabricated 0. */
  unrealized_pl?: number;
  /** Dollars; today's session unrealized P&L per Alpaca. Typed-absence. */
  unrealized_intraday_pl?: number;
  /** Dollars per share; prior session close per Alpaca. Typed-absence. */
  lastday_price?: number;
}

export interface BrokerPositionFetcher {
  /**
   * Fetch position for one symbol. Throws on network/auth errors. Returns
   * `null` ONLY if the broker explicitly reports the symbol has NO position
   * (not a fetch failure).
   */
  fetchPosition(symbol: string, ts: Date): Promise<BrokerPosition | null>;

  /**
   * List every currently-open broker position. Throws on network/auth errors.
   * Live impl MUST populate {market_value, current_price} on every row.
   */
  listOpenPositions?(ts: Date): Promise<BrokerPosition[]>;
}

// ────────────────────────────────────────────────────────────────────
// Shortability surface (adapter: alpaca-shortability-fetcher.ts)
// ────────────────────────────────────────────────────────────────────

/** Per-symbol shortability snapshot. Pre-trade gate for SHORT entries. */
export interface BrokerShortability {
  symbol: string;
  /**
   * Authoritative pre-trade gate. Alpaca composes ETB-list membership +
   * marginability into this single boolean.
   */
  shortable: boolean;
  /** Diagnostic — surfaced into reconciliation payloads only. */
  easy_to_borrow: boolean | null;
  fetched_at: Date;
}

export interface BrokerShortabilityFetcher {
  /**
   * Fetch shortability for one symbol. Throws on 5xx/network/auth errors
   * (DEC-034 (3) propagation). Inactive / delisted / unknown-symbol
   * returns `shortable: false` EXPLICITLY — never default-on-failure.
   */
  fetchShortability(symbol: string, ts: Date): Promise<BrokerShortability>;
}

// ────────────────────────────────────────────────────────────────────
// Order submission surface (adapter: alpaca-order-submitter.ts)
// ────────────────────────────────────────────────────────────────────

export interface BrokerOrderRequest {
  symbol: string;
  /** Integer whole shares. */
  qty: number;
  side: 'buy' | 'sell';
  /** `limit` for standard entries. `market` reserved for parallel-cover legs. */
  type: 'limit' | 'market';
  /** TIF=DAY. */
  time_in_force: 'day';
  /** Dollars; > 0 for limit; ignored for market. */
  limit_price: number;
  /** Per-target-per-tick idempotency key (generated by the submitter caller). */
  client_order_id: string;
}

/** Broker response on successful POST. Equivalent to Alpaca /v2/orders 200 subset. */
export interface BrokerOrderAcceptance {
  order_id: string;
  client_order_id: string;
  /** Broker-reported lifecycle: 'new' / 'pending_new' / 'accepted' / etc. */
  status: string;
  /** Broker-side acceptance timestamp. */
  submitted_at: Date;
}

export interface BrokerOrderSubmitter {
  submitOrder(req: BrokerOrderRequest, ts: Date): Promise<BrokerOrderAcceptance>;
}

// ────────────────────────────────────────────────────────────────────
// Fill polling surface (adapter: alpaca-fill-fetcher.ts)
// ────────────────────────────────────────────────────────────────────

/**
 * Fill snapshot. `filled: true` requires `filled_qty === requested_qty`
 * (atomic fill; partial-fill branch deferred to the analog of DW-140).
 */
export interface BrokerFillResult {
  order_id: string;
  filled: boolean;
  filled_qty: number;
  avg_fill_price: number | null;
  fetched_at: Date;
}

export interface BrokerFillFetcher {
  fetchFill(order_id: string, ts: Date): Promise<BrokerFillResult>;
}

// ────────────────────────────────────────────────────────────────────
// Order cancellation surface (adapter: alpaca-order-canceller.ts)
// ────────────────────────────────────────────────────────────────────

/**
 * Order cancellation. Required for the W3.8 marketable-limit cancel-and-
 * replace escalation (submit-without-cancel is incomplete broker parity;
 * canceller authorized by name in the W3.2.a operator ruling). Idempotent
 * at the broker boundary — cancelling an already-terminal order is a no-op
 * (adapter maps 422 → no-op per Alpaca's terminal-order semantics).
 */
export interface BrokerOrderCanceller {
  cancelOrder(order_id: string, ts: Date): Promise<void>;
}