#!/usr/bin/env -S deno run --allow-read --allow-write --allow-run --allow-env

/**
 * restore-lockfiles-v3 — Catalog #58 RESOLVED-structurally (Option 2 auto-restore).
 *
 * Runs on the CI runner BEFORE Gate 0a (`check-lockfile-versions.ts`). For each
 * required lockfile, if its top-level `version` is anything other than "3", the
 * file is removed and regenerated by invoking `deno cache --lock=<path>
 * --lock-write` under whatever Deno binary the CI runner has pinned. CI pins
 * Deno 1.46.3, which emits lockfile format v3 only — so the regeneration is
 * a structurally-guaranteed v5→v3 normalization. The committed lock in the
 * repo may still be v5 (the Lovable sandbox writes those); each CI run
 * self-heals it before the gate reads it.
 *
 * This replaces the per-commit manual `git show <sha>:deno.lock > deno.lock`
 * dance the operator has been running ~5x this session. The recurrence class
 * does not disappear (the sandbox keeps writing v5), but it becomes invisible
 * to CI (auto-fixed).
 *
 * SAFETY:
 *   - Only runs when a v5 lock is actually detected (no-op on clean v3 repo).
 *   - Uses `deno cache --lock-write` against the SAME entrypoint set the
 *     `strong-evidence` job's "Warm Deno cache" step uses; lockfile content
 *     stays in lockstep with what the rest of CI consumes.
 *   - Read-only on disk except for the lockfile itself + Deno's module cache.
 *   - Exits non-zero (and prints a clear marker) if regeneration fails — the
 *     gate still surfaces the divergence, just with a "regen-failed" reason
 *     instead of "raw v5 detected".
 *
 * INVARIANT: this script MUST NOT replace Gate 0a — it RUNS BEFORE it. Gate 0a
 * remains the assertion that, after self-heal, both locks ARE at v3. If the
 * regen path silently fails to produce a v3 lock, Gate 0a still fires.
 */

import { EXPECTED_LOCKFILE_VERSION } from './check-lockfile-versions.ts';

interface LockSpec {
  /** Path to the lockfile (relative to the CWD where this script runs). */
  lockPath: string;
  /** Working directory for the `deno cache` regeneration call. */
  cwd: string;
  /**
   * Optional `--config=` for the regen call (matches what the matching
   * "Warm Deno cache" entry uses).
   */
  configPath?: string;
  /**
   * How to discover the entrypoint set for `deno cache`. Either a static list
   * (root) or a glob-walk descriptor (functions tree).
   */
  entrypoints:
    | { kind: 'static'; paths: string[] }
    | { kind: 'walk'; rootDir: string; suffix: string; excludeDirs: string[] };
}

/**
 * The exact entrypoint sets the `strong-evidence.yml` "Warm Deno cache" step
 * uses (lines 105-119 of the workflow). Keeping these in lockstep is the
 * load-bearing invariant — if the workflow's warm-cache list drifts, this
 * script's regenerated lock will not match what the rest of CI consumes.
 */
export const LOCKFILE_SPECS: LockSpec[] = [
  {
    lockPath: 'deno.lock',
    cwd: '.',
    entrypoints: {
      kind: 'static',
      paths: [
        'scripts/check-audit-writer-trap.ts',
        'scripts/check-sentinel-patterns.ts',
        'scripts/check-wall-clock.ts',
        'scripts/check-paper-only-url.ts',
        'scripts/check-unguarded-parsefloat.ts',
        'scripts/check-catch-returns-zero.ts',
        'scripts/check-edge-imports.ts',
        'scripts/check-src-imports.ts',
        'scripts/check-eligibility-bypass.ts',
        'scripts/check-verify-after-mutation.ts',
        'scripts/check-supabase-client-specifier.ts',
        'scripts/check-handler-liveness-markers.ts',
        'supabase/functions/_shared/longshort-verifiers/longshort-verifiers_test.ts',
      ],
    },
  },
  {
    lockPath: 'supabase/functions/deno.lock',
    cwd: 'supabase/functions',
    configPath: 'deno.json',
    entrypoints: {
      kind: 'walk',
      rootDir: 'supabase/functions',
      suffix: '_test.ts',
      excludeDirs: ['node_modules'],
    },
  },
];

function readVersionField(path: string): string | null {
  try {
    const txt = Deno.readTextFileSync(path);
    const j = JSON.parse(txt) as { version?: unknown };
    return typeof j.version === 'string' ? j.version : null;
  } catch (e) {
    if (e instanceof Deno.errors.NotFound) return null;
    throw e;
  }
}

async function denoMajorVersion(): Promise<number> {
  try {
    const cmd = new Deno.Command('deno', { args: ['--version'], stdout: 'piped' });
    const { stdout } = await cmd.output();
    const txt = new TextDecoder().decode(stdout);
    const m = txt.match(/deno\s+(\d+)\./);
    return m ? Number(m[1]) : 1;
  } catch {
    return 1;
  }
}

function walkTests(rootDir: string, suffix: string, excludeDirs: string[]): string[] {
  const out: string[] = [];
  const stack: string[] = [rootDir];
  while (stack.length > 0) {
    const dir = stack.pop()!;
    for (const entry of Deno.readDirSync(dir)) {
      if (entry.isDirectory) {
        if (excludeDirs.includes(entry.name)) continue;
        stack.push(`${dir}/${entry.name}`);
      } else if (entry.isFile && entry.name.endsWith(suffix)) {
        // Path relative to the spec.cwd is what `deno cache` needs.
        out.push(`${dir}/${entry.name}`);
      }
    }
  }
  return out;
}

async function regenerate(spec: LockSpec): Promise<void> {
  const args = ['cache'];
  if (spec.configPath) args.push(`--config=${spec.configPath}`);
  // The regenerated lock path is relative to spec.cwd.
  const lockRelative = spec.lockPath.startsWith(spec.cwd + '/')
    ? spec.lockPath.slice(spec.cwd.length + 1)
    : spec.lockPath;
  args.push(`--lock=${lockRelative}`);
  // Deno 1.x requires the explicit --lock-write flag to write a missing lock;
  // Deno 2.x removed the flag (writing is implicit when --lock is given and
  // the file is absent). Detect and adapt so this script is runnable under
  // either binary — CI uses 1.46.3 (the production target), the Lovable
  // sandbox uses 2.x (local-verification only).
  if (await denoMajorVersion() < 2) args.push('--lock-write');

  let entryList: string[];
  if (spec.entrypoints.kind === 'static') {
    entryList = spec.entrypoints.paths;
  } else {
    entryList = walkTests(
      spec.entrypoints.rootDir,
      spec.entrypoints.suffix,
      spec.entrypoints.excludeDirs,
    );
    // Make entrypoints relative to spec.cwd.
    entryList = entryList.map((p) =>
      p.startsWith(spec.cwd + '/') ? p.slice(spec.cwd.length + 1) : p
    );
  }
  args.push(...entryList);

  // Remove the v5 lock first so deno regenerates from scratch (avoids
  // "Unsupported lockfile version '5'" under CI's Deno 1.46.3).
  try {
    Deno.removeSync(spec.lockPath);
  } catch (e) {
    if (!(e instanceof Deno.errors.NotFound)) throw e;
  }

  const cmd = new Deno.Command('deno', {
    args,
    cwd: spec.cwd,
    stdout: 'inherit',
    stderr: 'inherit',
  });
  const { code } = await cmd.output();
  if (code !== 0) {
    throw new Error(
      `restore-lockfiles-v3: deno cache regeneration failed for ${spec.lockPath} (exit ${code})`,
    );
  }
}

export async function restoreAll(): Promise<{ healed: string[]; alreadyClean: string[] }> {
  const healed: string[] = [];
  const alreadyClean: string[] = [];
  for (const spec of LOCKFILE_SPECS) {
    const v = readVersionField(spec.lockPath);
    if (v === EXPECTED_LOCKFILE_VERSION) {
      alreadyClean.push(spec.lockPath);
      continue;
    }
    console.log(
      `restore-lockfiles-v3: ${spec.lockPath} at version ${JSON.stringify(v)} ` +
        `→ regenerating at v${EXPECTED_LOCKFILE_VERSION} under pinned Deno`,
    );
    await regenerate(spec);
    const after = readVersionField(spec.lockPath);
    if (after !== EXPECTED_LOCKFILE_VERSION) {
      throw new Error(
        `restore-lockfiles-v3: regeneration of ${spec.lockPath} produced version ${JSON.stringify(after)} (expected ${EXPECTED_LOCKFILE_VERSION}) — Deno binary may not be 1.46.3-pinned`,
      );
    }
    healed.push(spec.lockPath);
  }
  return { healed, alreadyClean };
}

if (import.meta.main) {
  const { healed, alreadyClean } = await restoreAll();
  if (healed.length === 0) {
    console.log(
      `restore-lockfiles-v3: NO-OP — all ${alreadyClean.length} lockfile(s) already at v${EXPECTED_LOCKFILE_VERSION}`,
    );
  } else {
    console.log(
      `restore-lockfiles-v3: HEALED ${healed.length} lockfile(s) [${healed.join(', ')}]; ${alreadyClean.length} already clean`,
    );
  }
}