// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sftatlxatbdrotivxcip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmdGF0bHhhdGJkcm90aXZ4Y2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2OTIyNDMsImV4cCI6MjA5NDI2ODI0M30.ItD8UTfiWsWc1_f8iST4ahyypErCRIjjWeA-oswHKs8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});